language: node_js
node_js:
  - '4'
  - '6'
  - '8'
  - '10'
  - '12'
env:
  - ACORN_VERSION=6
  - ACORN_VERSION=7

before_script:
  - 'if [ $ACORN_VERSION != 7 ]; then npm install -D acorn@$ACORN_VERSION; fi'
